apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result-nodeport-svc
spec:
  type: NodePort
  ports:
  - name: "result-service"
    port: 80
    targetPort: 80
  selector:
    app: result
