name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
jobs:
- job: Job_1
  displayName: Ubuntu Agent
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
  - task: Docker@2
    displayName: Build Image
    inputs:
      repository: 619108111967.dkr.ecr.us-east-1.amazonaws.com/vote
      command: build
      tags: $(Build.BuildNumber)
      addPipelineData: false
      addBaseImageData: false
  - task: ECRPushImage@1
    displayName: Push Image To ECR
    inputs:
      awsCredentials: 5e801cd0-f32c-4a2d-9d48-b94996a59fcc
      regionName: us-east-1
      sourceImageName: 619108111967.dkr.ecr.us-east-1.amazonaws.com/vote
      sourceImageTag: $(Build.BuildNumber)
      repositoryName: vote
      pushTag: $(Build.BuildNumber)
...
